# Generated by Django 2.0 on 2018-10-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20181013_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='obp_pwd',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='obp_username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
