# Generated by Django 2.0 on 2018-10-13 23:01

from django.db import migrations, models
import hello.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20181013_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='obp_username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='obp_pwd',
            field=models.CharField(default=hello.models.make_password, max_length=16),
        ),
    ]
